### PR TITLE
New: add `max-lines` rule

### PR DESCRIPTION
**Pull request by rygine**

### CODE REVIEW

**Comment by blazzy** [comment]
Skip comments? What if I need to share all my deep thoughts and feelings?

LGTM.

image

**Comment by briantrice** [comment]
Yeah, I do tend to like comments, in a vaguely-literate way.

OTOH as the owner of the one offending file right now, it's livable. I say we adopt and "try it on" to see how it feels. 👍

**Review by paulyoung — APPROVED** [review]
As we discussed in person, I think 500 is a bit arbitrary so I'm curious how it will work out but generally think that this is a good idea.

**Comment by paulyoung** [comment]
Yo @blazzy, @briantrice – LGTM and 👍 is old and busted, approving is the new hotness

**Comment by rygine** [comment]
note: it's just a warning. it will not affect builds. it's more of a, "hey, yo code is big. should it really be that big? can it be smaller?"

**Comment by blazzy** [comment]
Missed that fact on review. This is why the strings `"warn"`, `"error"`, and `"off"` are so much nicer.

I'd favor a build breaking error.

**Comment by rygine** [comment]
once @briantrice starts working on the histogram again, we can upgrade this to "error." it's the only file that would cause the error, and it would break all builds.

and we can also refactor the numbers into strings for easier reading at the same time. :)

**Review by leland-kwong — APPROVED** [review]

**Comment by leland-kwong** [comment]
500 seems like a decent number to start with. If anything, some limitation is better than none 👍

**Pull request merged**
